### ISSUE TITLE
Permission denied: 'exportanalog'

### ISSUE THREAD

**Issue by jthermiz** [LorenFrankLab/rec_to_binaries#11]
I use the example code in the README to convert a rec file and receive this error:

`PermissionError: [Errno 13] Permission denied: 'exportanalog'`

[permission_error.txt](https://github.com/LorenFrankLab/rec_to_binaries/files/5897462/permission_error.txt)

[test_py.txt](https://github.com/LorenFrankLab/rec_to_binaries/files/5897463/test_py.txt)

Any ideas on what is happening here?

**Comment by edeno** [comment]
`rec_to_binaries` is mostly just a wrapper for the Trodes export functions. So the python code is trying to run this in the command line in bash:
```bash
exportanalog -rec /home/jhermiz/Desktop/echip/raw/20210128/20210128_echip_06_r3.rec -outputdirectory /home/jhermiz/Desktop/echip/preprocessing/20210128 -output 20210128_echip_06_r3
```
where `exportanalog` is a function from Trodes. You can actually directly run this in the command line and you will see that you get the same error. If you were to run:
```bash
sudo exportanalog -rec /home/jhermiz/Desktop/echip/raw/20210128/20210128_echip_06_r3.rec -outputdirectory /home/jhermiz/Desktop/echip/preprocessing/20210128 -output 20210128_echip_06_r3
```
It would probably run successfully assuming you're a user with sudo privileges on your machine.

So, to solve this, I would make sure Trodes is on your path and then change the permissions on the Trodes directory (`chmod` the directory). Does that make sense?
