### ISSUE TITLE
virga-05 libGL error

### ISSUE THREAD

**Issue by acomrie** [LorenFrankLab/rec_to_binaries#13]
When running rec to nwb conversions on virga-05, I get the following error, which seems to lead to subsequent fatal errors: `error while loading shared libraries: libGL.so.1: cannot open shared object file: No such file or directory`

This error seems to occur when running via jupyter, but not bash. Possibly related to Trodes versions. This error was avoided by swapping to another computer for the time being.

Not sure who to tag - potentially @edeno, though don't think he has sudo powers, so perhaps @lfrank? Virga-05 may need some general clean-up as well. Thank you!

**Comment by lfrank** [comment]
Should be fixed; please try again.

**Comment by acomrie** [comment]
looks like the libGL issue is resolved at least, thanks!
