### ISSUE TITLE
TrodesAnimalInfo does not have paths to preprocessed LFP/spike

### ISSUE THREAD

**Issue by jihyunbak** [LorenFrankLab/rec_to_binaries#8]
## Summary

I am trying to convert the preprocessed binaries to HDF5 files (related: PR #7 ). But nothing happens for LFP and spike conversion.

The immediate cause of this, I think, is that the `preproc_LFP_paths` and preproc_spike_path` are empty tables.

## Prerequisite

After preprocessing, I would do:

```python
data_path = '/my/data/path'
animal_name = 'kf19'
out_dir = 'my/preprocessing/path'
dates = ['20170901']

anim = td.TrodesAnimalInfo(data_path, animal_name,
                           out_dir=out_path, dates=dates)
```

## Current behavior

I get an empty table for the LFP (or spike) paths:

```python
anim.preproc_LFP_paths
```

  | date | epoch | label_ext | datatype | ntrode | channel | timestamp_file | time_label | export_logfile | dir_index | path
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --

## Expected behavior

The table for the DIO paths (as well as pos) looks all right.

```python
anim.preproc_dio_paths
```

  | date | epoch | label_ext | datatype | time_label | direction | channel | export_logfile | dir_index | path
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
20170901 | (1,) |   | DIO |   | in | 1.0 | False | 0 | /home/jhbak/Output/nwb_output/pilot/kf19/prepr...
20170901 | (1,) |   | DIO |   | in | 2.0 | False | 0 | /home/jhbak/Output/nwb_output/pilot/kf19/prepr...
20170901 | (1,) |   | DIO |   | in | 3.0 | False | 0 | /home/jhbak/Output/nwb_output/pilot/kf19/prepr...
20170901 | (1,) |   | DIO |   | in | 4.0 | False | 0 | /home/jhbak/Output/nwb_output/pilot/kf19/prepr...
20170901 | (1,) |   | DIO |   | in | 5.0 | False | 0 | /home/jhbak/Output/nwb_output/pilot/kf19/prepr...
... | ... | ... | ... | ... | ... | ... | ... | ... | ...
20170901 | (2,) |   | DIO |   | out | 18.0 | False | 5 | /home/jhbak/Output/nwb_output/pilot/kf19/prepr...
20170901 | (2,) |   | DIO |   | out | 19.0 | False | 5 | /home/jhbak/Output/nwb_output/pilot/kf19/prepr...
20170901 | (2,) |   | DIO |   | out | 20.0 | False | 5 | /home/jhbak/Output/nwb_output/pilot/kf19/prepr...
20170901 | (2,) |   | DIO |   | out | 21.0 | False | 5 | /home/jhbak/Output/nwb_output/pilot/kf19/prepr...
20170901 | (2,) |   | DIO | None | None | NaN | True | 5 | /home/jhbak/Output/nwb_output/pilot/kf19/prepr...

I am copying from my Jupyter notebook output cell.

**Comment by jihyunbak** [comment]
If this is relevant, the [epoch].analog and [epoch].mda folders in my proprocessing path have data.

In the analog folder of an example epoch:

```
20170901_kf19_01_s1.analog_Ain1.dat  20170901_kf19_01_s1.analog_Ain6.dat
20170901_kf19_01_s1.analog_Ain2.dat  20170901_kf19_01_s1.analog_Ain7.dat
20170901_kf19_01_s1.analog_Ain3.dat  20170901_kf19_01_s1.analog_Ain8.dat
20170901_kf19_01_s1.analog_Ain4.dat  20170901_kf19_01_s1.exportanalog.log
20170901_kf19_01_s1.analog_Ain5.dat  20170901_kf19_01_s1.timestamps.dat
```

In the mda folder:

```
20170901_kf19_01_s1.exportmda.log  20170901_kf19_01_s1.nt26.mda
20170901_kf19_01_s1.nt1.mda        20170901_kf19_01_s1.nt27.mda
20170901_kf19_01_s1.nt10.mda       20170901_kf19_01_s1.nt28.mda
20170901_kf19_01_s1.nt11.mda       20170901_kf19_01_s1.nt29.mda
20170901_kf19_01_s1.nt12.mda       20170901_kf19_01_s1.nt3.mda
20170901_kf19_01_s1.nt13.mda       20170901_kf19_01_s1.nt30.mda
20170901_kf19_01_s1.nt14.mda       20170901_kf19_01_s1.nt31.mda
20170901_kf19_01_s1.nt15.mda       20170901_kf19_01_s1.nt32.mda
20170901_kf19_01_s1.nt16.mda       20170901_kf19_01_s1.nt33.mda
20170901_kf19_01_s1.nt17.mda       20170901_kf19_01_s1.nt34.mda
20170901_kf19_01_s1.nt18.mda       20170901_kf19_01_s1.nt35.mda
20170901_kf19_01_s1.nt19.mda       20170901_kf19_01_s1.nt36.mda
20170901_kf19_01_s1.nt2.mda        20170901_kf19_01_s1.nt4.mda
20170901_kf19_01_s1.nt20.mda       20170901_kf19_01_s1.nt5.mda
20170901_kf19_01_s1.nt21.mda       20170901_kf19_01_s1.nt6.mda
20170901_kf19_01_s1.nt22.mda       20170901_kf19_01_s1.nt7.mda
20170901_kf19_01_s1.nt23.mda       20170901_kf19_01_s1.nt8.mda
20170901_kf19_01_s1.nt24.mda       20170901_kf19_01_s1.nt9.mda
20170901_kf19_01_s1.nt25.mda       20170901_kf19_01_s1.timestamps.mda
```

**Comment by jihyunbak** [comment]
Oh… maybe it is actually looking for .LFP and .spike folders, which do not exist in my case.
Would be great if you could confirm @edeno !

~And if this is the case, how do I generate these LFP and spike binaries?~ …... Ok, just figured out that these switches were turned off in the RawToNWBBuilder, which I used for calling this package.

**Comment by edeno** [comment]
@jihyunbak so is there still an issue or was the solution just to turn on the appropriate switches?

**Comment by edeno** [comment]
@jihyunbak  so was the problem not turning on the LFP and spike switches? The directories won't be made if they aren't turned on.

**Comment by jihyunbak** [comment]
Thanks @edeno - yes, just checked that the directories were made and pointed to successfully when I turned on the switch. Closing this issue.

I am getting another error downstream though, where TrodesPreprocessingSpikeEpoch calls TrodesSpikeBinaryLoader through multiprocessing... I will look into it and ask for help if it persists.
